// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suyecfnyctsdufyyojjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eWVjZm55Y3RzZHVmeXlvamp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDQ4MjUsImV4cCI6MjA4ODEyMDgyNX0.NwWCSxy96ez12-T0e-f-U9qC2o0dJAaEYZU6LKExT5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});